---
- name: Install VS Code Insiders
  shell: |
    type code-insiders >/dev/null 2>&1 || {
      wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg;
      sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/packages.microsoft.gpg;
      sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code-insiders stable main" > /etc/apt/sources.list.d/vscode-insiders.list';
      sudo apt update;
      sudo apt install code-insiders -y;
    }
  args:
    executable: /bin/bash
