---
- name: Install Node.js 24 using NodeSource
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
    sudo apt install -y nodejs
  args:
    executable: /bin/bash
